branch-defaults:
  development:
    environment: null
    group_suffix: null
deploy:
  artifacct: ./www/Archive.zip
global:
  application_name: udagram-cloud-assignment
  branch: null
  default_ec2_keyname: kumar_aws
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
